export const READING_SESSION_INACTIVITY_MS = 3 * 60 * 1_000
export const READING_SESSION_HEARTBEAT_MS = 45 * 1_000
export const READING_SESSION_POSITION_SAVE_MS = 1_500
export const READING_SESSION_END_GRACE_MS = 750
